### PR TITLE
Fix/mpecdh UI

### LINKED ISSUE #68: Fix mpecdh UI / UX
## 1. Description

The UI / UX of the mpecdh deployment as implemented in #57 / #66 can be improved to guide the user through the deployment / contribution steps.

### 1.1 Why

Right now we show transaction and contract (deployment) information which is highly technical and can confuse the user. In addition to that the layout looks slightly off compared to the rest of the settings page.

The buttons are also enabled, even if an action was already taken by the respective user (e.g. if a contract deployment is currently pending, the user already contributed, ...).

### 1.2 Proposed Solution

Rather than displaying detailed transaction and contract (deployment) information we could use regular UI elements to signal in which stage of the deployment / setup we are.

I'm not 100% sure how this could look like, but we could re-use the existing buttons to signal in which step we are (e.g. changing the label to some descriptive message while also disabling the button).

Using the buttons for this could get ugly, though so another solution could be to display a list with all the steps that must be taken and how far along we are in this (user journey). A component we could use for this is the MUI timeline: https://mui.com/material-ui/react-timeline/

We should also incorporate some information as to who of the Safe signers needs to do what (e.g. "Waiting for 0x1234 to contribute..."). The buttons should then be enabled / disabled accordingly (e.g. if we're waiting for Alice to contribute, then only Alice should be able to click the button).

## 2. Test Cases

This is mostly a visual exercise. We should work though a full deployment, contribution and therefore setup while keeping track of the states in which we're in (and whether the UI reflects those steps accurately).

## 3. Dependencies

We're depending on the mpecdh project in order for this to work properly.

Refs #7 #57 #66

### PR DESCRIPTION
**Pull request by pardis-toolabi**
closes #68

### CODE REVIEW

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 1]
```diff
@@ -138,15 +142,59 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
       const ethersSigner = await browserProvider.getSigner()
       const current = await ceremony_helper.status(ethersSigner)
       setStatus(current)
-      setBlocking(await ceremony_helper.blocking())
+      const blockingList = await ceremony_helper.blocking()
+      console.log('Blocking list:', blockingList)
```
Comment (chiefbiiko) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]: Can go once confident.

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 2]
```diff
@@ -369,57 +451,137 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
+          <Box sx={{ 
+            p: 2, 
+            mt: 2,
+            backgroundColor: 'background.paper', 
+            borderRadius: 1,
+            border: '1px solid',
+            borderColor: 'divider'
+          }}>
+            <Typography variant="caption" sx={{ fontSize: '0.75rem', color: 'text.secondary', display: 'block' }}>
+            How to set up shielded account ?
```
Comment (chiefbiiko) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]:
```suggestion
            How to set up your Safe's shielded account?
```

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 3]
```diff
@@ -369,57 +451,137 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
+            </Typography>
+            <Typography variant="caption" sx={{ fontSize: '0.75rem', color: 'text.secondary', display: 'block', mt: 0.5 }}>
+              1. Deploy the secret sharing contract (MPECDH)
```
Comment (chiefbiiko) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]: The term secret sharing is more associated with key splitting techniques I think.

Would reformulate


```suggestion
              1. Deploy a multi-party key exchange coordination contract for your Safe (owners)
```

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 4]
```diff
@@ -369,57 +451,137 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
+            </Typography>
+            <Typography variant="caption" sx={{ fontSize: '0.75rem', color: 'text.secondary', display: 'block' }}>
+              2. Contribute to ceremony  ({safe.owners.length - 1} {safe.owners.length - 1 === 1 ? 'round' : 'rounds'})
```
Comment (chiefbiiko) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx:467]:
```suggestion
              2. Contribute to the multi-party key exchange in turns 
```

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 5]
```diff
@@ -369,57 +451,137 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
+            </Typography>
+            <Typography variant="caption" sx={{ fontSize: '0.75rem', color: 'text.secondary', display: 'block' }}>
+              3. Wait for other owners to contribute
```
Comment (chiefbiiko) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]:
```suggestion
```

Would remove this entire Typography element because hope the above "in turns" makes clear that contributions are to be made recurringly and with a wait, and also this has a duplicate 3. prefix.

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 6]
```diff
@@ -369,57 +451,137 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
+              2. Contribute to ceremony  ({safe.owners.length - 1} {safe.owners.length - 1 === 1 ? 'round' : 'rounds'})
+            </Typography>
+            <Typography variant="caption" sx={{ fontSize: '0.75rem', color: 'text.secondary', display: 'block' }}>
+              3. Wait for other owners to contribute 
+            </Typography>
+            <Typography variant="caption" sx={{ fontSize: '0.75rem', color: 'text.secondary', display: 'block' }}>
+              3. Derive seed
+            </Typography>
+            <Typography variant="caption" sx={{ fontSize: '0.75rem', color: 'text.secondary', display: 'block' }}>
+              4. Register name.bay alias
```
Comment (chiefbiiko) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]:
```suggestion
              4. Optionally register a name.bay alias for your shielded address
```

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 7]
```diff
@@ -369,57 +451,137 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
+                    </Box>
+                  )}
+                  {hasContributed && (
+                    <Typography variant="body2" sx={{ color: 'success.main', fontSize: '0.875rem' }}>
+                      Contribution submitted.
+                    </Typography>
+                  )}
+                    </>
+                )}
+                {isReady && !keyPair &&(
```
Comment (chiefbiiko) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]: Once `isReady===true` we should immediately derive the shared secret without additional user interaction / button click.

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 8]
```diff
@@ -465,8 +627,8 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
                 </Button>
               </Box>
             ) : (
-              <Typography variant="body2" color="text.secondary">
-                Derive the shielded seed through the MPECDH ceremony to unlock alias registration.
+              <Typography variant="body2" color="text.secondary" sx={{ textAlign: 'center' }}>
+                  Complete the shielded account setup to unlock shielded transactions.
```
Comment (chiefbiiko) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]:
```suggestion
                  Complete the shielded account setup to enable shielded transactions.
```

**Review by chiefbiiko — CHANGES_REQUESTED** [review]
Nice, if in the end you could please also rewrite the commits a bit to have some `refactor:`s where functionality/flow has been changed and else collapse some of those chore commits.

File: apps/web/src/components/settings/ShieldedAccount/index.tsx (hunk 4 above)
Comment (pardis-toolabi) [reply apps/web/src/components/settings/ShieldedAccount/index.tsx:467]: I think it's more clear if the user knows the number of contribution they have to make, they might not make the connection just by having the total rounds data

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 9]
```diff
@@ -360,7 +434,7 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
             Shielded account
           </Typography>
           <Stack direction="column" spacing={1} mt={2}>
-            {expectedAddress && (
+            {/* {expectedAddress && (
```
Comment (pmuens) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]: Can this section be removed?

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 10]
```diff
@@ -340,6 +390,30 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
     setRegisterAliasError(undefined)
   }
 
+const canContribute = useMemo(() => {
+  if (!signer?.address) return false
+  if (mpecdhAddress && !isReady && blocking.length === 0) return true
+  return blocking.some(addr => addr.toLowerCase() === signer.address.toLowerCase())
+}, [signer?.address, blocking, mpecdhAddress, isReady])
+
+  const isDeploymentPending = useMemo(() => {
```
Comment (pmuens) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]: This code block can be unindented by two spaces.

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 11]
```diff
@@ -369,57 +443,122 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
               </Typography>
-            )}
+            )} */}
             {deploymentHash && (
               <Typography variant="body2" title={deploymentHash}>
                 Deployment tx: <code>{shortenHex(deploymentHash, 6)}</code>
               </Typography>
             )}
-            {pendingTxs.length > 0 &&
+            {/* {pendingTxs.length > 0 &&
```
Comment (pmuens) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]: Can this section be removed?

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 12]
```diff
@@ -369,57 +443,122 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
               pendingTxs.map((item) => (
                 <Typography key={item.hash} variant="body2" title={item.hash}>
                   Pending: <code>{shortenHex(item.hash, 6)}</code> – {item.confirmationStatus}
                 </Typography>
-              ))}
+              ))} */}
             {blocking.length > 0 && (
               <Typography variant="body2">
                 Blocking: {blocking.map((addr: string) => shortenHex(addr, 4)).join(', ')}
```
Comment (pmuens) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]: I'd propose to rename this to "Blocking Address" or "Blocking User Address". When I first did the key exchange myself I didn't know what was "Blocking" ("a contract deployment?", "a transaction that didn't go through?", "something else entirely?")

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 13]
```diff
@@ -369,57 +443,122 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
-                onClick={handleLogin}
-                disabled={isLoading || !mpecdhAddress || !isReady}
-                title="Derive shared seed and register shielded key"
-              >
-                Derive seed
-              </Button>
-            </Box>
+            {!mpecdhAddress && (
+              <Box component="form" onSubmit={handleDeploy} sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center', justifyContent: 'center' }}>
+                <Tooltip
```
Comment (pmuens) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx:484]: I get the idea for the tooltip, but it didn't occur to me personally that hovering over the respective elements reveals such helpful information.

As an improvement we could display "help"-related messages such as "Deployment transaction is pending. Check the Transactions list to approve and execute." directly in the UI without reaching for a tooltip.

This could also be a "me thing", though so I'm also totally fine if we think it's obvious for others and therefore not necessary.

**Review by pmuens — COMMENTED** [review]
I tested this and it works as advertised. Added a nit comments with things we could improve. Other than that I'd say it's LGTM.

File: apps/web/src/components/settings/ShieldedAccount/index.tsx (hunk 13 above)
Comment (pardis-toolabi) [reply apps/web/src/components/settings/ShieldedAccount/index.tsx:484]: I think if the user is in the process of setting up the account they can get the info they need with the hovers,  adding more information directly might make the UI too busy

Comment (pardis-toolabi) [reply apps/web/src/components/settings/ShieldedAccount/index.tsx:484]: we can add a help link that will redirect them to a descriptive help document, explaining the steps visually and in details

File: apps/web/src/components/settings/ShieldedAccount/index.tsx [hunk 14]
```diff
@@ -138,15 +142,106 @@ export default function ShieldedAccount({ sx }: { sx: SxProps }) {
...
     }
   }
 
+  useEffect(() => {
+    if (isReady) {
+      setHasContributed(false)
+    }
+  }, [isReady])
+
+  // Add this useEffect after line 156
```
Comment (pmuens) [inline apps/web/src/components/settings/ShieldedAccount/index.tsx]: This output can be removed.

File: apps/web/src/components/settings/ShieldedAccount/index.tsx (hunk 13 above)
Comment (pmuens) [reply apps/web/src/components/settings/ShieldedAccount/index.tsx:484]: Yes, that might be a better option. I agree that if you know how it works, then you kind of know what to do.

**Review by pmuens — APPROVED** [review]
Just a minor nit about a leftover comment. Other than that it looks good from a code perspective.

I couldn't test this manually again, unfortunately as I get a 403 when I try to spin up the testenv. But if nothing major changed, compared to the version I tested in my prior commit, then we should be GTM.

**Edit**: Just checked the commit you pushed and it's only concerned with a cleanup, so it's LGTM.
